# Site settings
title: KikiDesign
email: kikismail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  一枚码农，极简主义者
baseurl: "" # the subpath of your site, e.g. /blog/
url: "kikidesign.github.io" # the base hostname & protocol for your site
github_username:  Kikidesign
lunr_search:
excludes: [atom.xml]

# Build settings
markdown: kramdown
