# Site settings
title: Kikidesign
email: kikismail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  an iOS Xcode programmer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://Kikidesign.cn” # the base hostname & protocol for your site
github_username:  Kikidesign

# Build settings
markdown: kramdown