# Site settings
title: KikiDesign
email: kikidesign@qq.com
description: > # this means to ignore newlines until "baseurl:"
  一枚码农，极简主义者
baseurl: "" # the subpath of your site, e.g. /blog/
url: "kikidesign.github.io" # the base hostname & protocol for your site
github_username:  Kikidesign
gems: ['jekyll-lunr-js-search']
lunr_search:
  excludes: [rss.xml, atom.xml]
# Build settings
markdown: kramdown
